# Generated by Django 5.0 on 2023-12-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccommodationHireApp', '0002_alter_user_avatar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_user',
            field=models.ImageField(upload_to=''),
        ),
    ]
