# Generated by Django 5.0 on 2023-12-16 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccommodationHireApp', '0004_alter_user_avatar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='AccommodationHireApp.role'),
        ),
    ]
