# Generated by Django 5.0 on 2023-12-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccommodationHireApp', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
